import { NoEncryption } from '@mui/icons-material';
import { Box, Button, Grid, Input } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styled from 'styled-components';
import { useEnsName } from 'wagmi';

import CardModule from '../components/CardModule';
import CoinPrices from '../components/functions/coinPrices';
import FavNFTModule from '../components/functions/collectNFTs';
import GasFees from '../components/functions/gasFees';
import InstallDAPPs from '../components/functions/installDAPPs';
import ReadLaters from '../components/functions/readLaters';
import VisitHistories from '../components/functions/visitHistories';
import styles from '../styles/Home.module.css';
import { users } from '../utils/apis';
import { fetchWrapped } from '../utils/apis/fetch';
import {
  colorfulButtonStyle,
  colorfulTextStyle,
} from '../utils/common-colorful-button';

const AddressButton = styled.span`
  ${colorfulTextStyle}
  margin-right:20px;
  font-weight: 600;
`;
function AddressSPAN(props: { address: string }) {
  const { data, isError, isLoading } = useEnsName({
    address: props.address as `0x${string}`,
  });

  if (isLoading) return <AddressButton>{props.address}</AddressButton>;
  if (isError) return <AddressButton>{props.address}</AddressButton>;
  return <AddressButton>{data}</AddressButton>;
}

const LoginButton = styled.button`
  ${colorfulButtonStyle}
`;
const Home: NextPage = () => {
  const [userInfo, setUserInfo] = useState<users>();

  async function fetchLoginInfo() {
    return new Promise((resolve, reject) => {
      fetchWrapped(process.env.NEXT_PUBLIC_APIBASE + '/users/me', {
        method: 'GET',
      })
        .then((json) => {
          if (json?.data?.address) {
            setUserInfo(json.data);
          } else {
            reject();
          }
        })
        .catch(reject);
    });
  }
  async function logout() {
    chrome.storage.local.set({ access_token: '' }, function () {});
    gotoLogin();
  }
  async function gotoLogin() {
    chrome.tabs.create({
      url: chrome.runtime.getURL('login.html'),
    });
  }
  const [logoURL, setLogoURL] = useState<string>();
  const [indexLogoURL, setIndexLogoURL] = useState<string>();
  useEffect(() => {
    fetchLoginInfo();
    const _logoURL = chrome?.runtime?.getURL('images/logo-128.png');
    setLogoURL(_logoURL);
    const _indexLogoURL = chrome?.runtime?.getURL('images/index-logo-2.png');
    setIndexLogoURL(_indexLogoURL);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>MetaPavo Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={logoURL} />
      </Head>
      <header className={styles.head}>
        <div className={styles.headInner}>
          <img src={indexLogoURL} style={{ height: '25px' }} />
          {userInfo?.address ? (
            <span>
              <AddressSPAN address={userInfo.address} />
              <a
                onClick={() => {
                  logout();
                }}
              >
                Logout
              </a>
            </span>
          ) : (
            <a
              onClick={() => {
                gotoLogin();
              }}
            >
              Login
            </a>
          )}
        </div>
      </header>
      <main className={styles.main}>
        <div className={styles.searchBg}>
          <Box>
            <input
              placeholder="Search by keyword/address/ens/dapp name"
              style={{
                width: '700px',
                margin: '0 auto',
                borderRadius: '20px',
                height: '40px',
                background: '#fff',
                border: 'none',
                textAlign: 'center',
                fontSize: '14px',
              }}
            />
          </Box>
        </div>
        <Grid
          container
          spacing={2}
          style={{ width: '1328px', margin: '40px auto' }}
        >
          <Grid item xs={8}>
            <CardModule title="My Collected NFTs">
              <FavNFTModule></FavNFTModule>
            </CardModule>
            <CardModule
              title="My Installed DAPPs"
              extra={<a href="#">DAPP Store</a>}
            >
              <InstallDAPPs></InstallDAPPs>
            </CardModule>
            <CardModule title="Read Laters">
              <ReadLaters></ReadLaters>
            </CardModule>
            <CardModule title="History">
              <VisitHistories></VisitHistories>
            </CardModule>
          </Grid>
          <Grid item xs={4}>
            <CardModule
              title="Gas"
              extra={<a href="https://ultrasound.money/">What's happening</a>}
            >
              <GasFees></GasFees>
            </CardModule>
            <CardModule title="BTC Price" extra={<a href="#">Setting</a>}>
              <CoinPrices symbol="BTCUSDT"></CoinPrices>
            </CardModule>
            <CardModule title="ETH Price" extra={<a href="#">Setting</a>}>
              <CoinPrices symbol="ETHUSDT"></CoinPrices>
            </CardModule>
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export default Home;
