import { Button, Grid } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { useEnsName } from 'wagmi';

import CardModule from '../components/CardModule';
import FavNFTModule from '../components/functions/collectNFTs';
import GasFees from '../components/functions/gasFees';
import InstallDAPPs from '../components/functions/installDAPPs';
import styles from '../styles/Home.module.css';
import { users } from '../utils/apis';
import { fetchWrapped } from '../utils/apis/fetch';

function AddressSPAN(props: { address: string }) {
  const { data, isError, isLoading } = useEnsName({
    address: props.address as `0x${string}`,
  });

  if (isLoading) return <span>{props.address}</span>;
  if (isError) return <span>{props.address}</span>;
  return <span>{data}</span>;
}
const Home: NextPage = () => {
  const [userInfo, setUserInfo] = useState<users>();

  async function fetchLoginInfo() {
    return new Promise((resolve, reject) => {
      fetchWrapped(process.env.NEXT_PUBLIC_APIBASE + '/users/me', {
        method: 'GET',
      })
        .then((json) => {
          if (json?.data?.address) {
            setUserInfo(json.data);
          } else {
            reject();
          }
        })
        .catch(reject);
    });
  }
  async function logout() {
    chrome.storage.local.set({ access_token: '' }, function () {});
    gotoLogin();
  }
  async function gotoLogin() {
    chrome.tabs.create({
      url: chrome.runtime.getURL('login.html'),
    });
  }
  useEffect(() => {
    fetchLoginInfo();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <head className={styles.head}>
        {userInfo?.address ? (
          <>
            <AddressSPAN address={userInfo.address} />
            <Button
              onClick={() => {
                logout();
              }}
            >
              Logout
            </Button>
          </>
        ) : (
          <Button
            onClick={() => {
              gotoLogin();
            }}
          >
            Login
          </Button>
        )}
      </head>
      <main className={styles.main}>
        <Grid
          container
          spacing={2}
          style={{ width: '1328px', margin: '0 auto' }}
        >
          <Grid item xs={8}>
            <CardModule title="My Collected NFTs">
              <FavNFTModule></FavNFTModule>
            </CardModule>
            <CardModule title="My Installed DAPPs">
              <InstallDAPPs></InstallDAPPs>
            </CardModule>
          </Grid>
          <Grid item xs={4}>
            <CardModule
              title="Gas"
              extra={<a href="https://ultrasound.money/">What happening</a>}
            >
              <GasFees></GasFees>
            </CardModule>
          </Grid>
        </Grid>
      </main>
    </div>
  );
};

export default Home;
