/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as pavoPassSol from "./PavoPass.sol";
export * as ownership from "./ownership";
export * as sbt from "./sbt";
